title: 
description: Руководство на ГК
theme: just-the-docs

url: https://rast164.github.io/gk_manual

aux_links:
  Сайт на GitHub: https://github.com/rast164/gk_manual

color_scheme: dark

back_to_top: true
back_to_top_text: "В начало страницы"
