title: 
description: Руководство на ГК
theme: just-the-docs

url: https://rast164.github.io/gk_manual

aux_links:
  Сайт на GitHub: https://github.com/rast164/gk_manual

color_scheme: dark

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
